name: Auto Update Charts

on:
  schedule:
    - cron: '0 19 * * *'  # This runs the workflow every day at 7:00 PM UTC
  workflow_dispatch:  # Allow manual trigger from GitHub UI if needed

jobs:
  update-charts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo 1
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt file

      - name: Run Python script
        run: |
          python eth_ema_chart.py  # Run your Python script to generate the charts

      - name: Checkout Repo 2 (Chart URLs Repo)
        uses: actions/checkout@v2
        with:
          repository: kimon222/crypto-charts  # Replace with the name of your second repo
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          path: repo2

      - name: Copy updated chart URL file
        run: |
          cp latest_chart_urls.txt crypto-charts/latest_chart_urls.txt  # Copy the updated text file

      - name: Commit and push to Repo 2
        run: |
          cd crypto-charts
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add latest_chart_urls.txt
          git commit -m "Update chart URLs"
          git push origin main  # Push to the main branch of Repo 2

