name: Auto Update Charts

on:
  schedule:
    - cron: '0 17 * * *'  # Runs daily at 7:00 PM Latvia time (UTC+2 → UTC 17:00)
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  update-charts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo 1 (Main Repo)
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt file

      - name: Run Python script
        env:
          IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}  # Pass secret to the Python script
        run: |
          python eth_ema_chart.py  # Run your Python script to generate the charts

      - name: Ensure latest_chart_urls.txt exists
        run: |
          touch latest_chart_urls.txt  # Create the file if it doesn't exist

      - name: Clean up image files
        run: |
          rm -f *.png  # Remove all .png files after upload

      - name: Checkout Repo 2 (Chart URLs Repo)
        uses: actions/checkout@v2
        with:
          repository: kimon222/chart-urls  # Correct repo name
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          path: chart-urls

      - name: Copy updated chart URL file
        run: |
          cp latest_chart_urls.txt chart-urls/latest_chart_urls.txt  # Copy the updated text file

      - name: Commit and push to Repo 2
        run: |
          cd chart-urls
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add latest_chart_urls.txt
          git commit -m "Update chart URLs" || echo "No changes to commit"
          git push origin main  # Push to the main branch of Repo 2
